[development]
dynaconf_merge = true

[development.db]
echo = true

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://127.0.0.1:8000", "http://127.0.0.1:8001"]

[production]
dynaconf_merge = true

[production.db]
echo = false

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.server]
cors_origins = ["http://localhost:8000", "http://localhost:8001"]